#!/bin/bash

start=1
end=11
for i in $(cat instances)
do
ssh -vi /home/michelle/artanis_1.0/key 'ubuntu@'$i /home/ubuntu/artanis/server_articles $start $end $1 $2
let start=$start+10; let end=$end+10
done


while [ 1 -gt 0 ]
do
n=0
for instance in $(cat instances)
do
prog=$(ssh -vi key -q 'ubuntu@'$i tail -n 1 /home/ubuntu/screenlog.0)
echo $prog | tr -s '\r' '\n' > screen_data
echo $instance'|'$(tail -n 1 screen_data) >> allscreens
let n=$n+1
done
clear
tail -n $n allscreens
done
