#!/bin/bash

start=1
end=10
for i in $(cat instances)
do
ssh -vi ~/key 'ubuntu@'$i screen -dmL
ssh -vi ~/key 'ubuntu@'$i 'screen -X stuff "source venv/bin/activate\n"'
ssh -vi ~/key 'ubuntu@'$i 'screen -X stuff "python /home/ubuntu/artanis/artanis.py -s "'$start'" -e "'$end'" -f 2011 -l 2012 -m articles\n"'
let start=$start+10
let end=$end+10
done
