#!/bin/bash

for instance in $(cat instances)
do
i=${instance//' '/''}
let c=$c+1
scp -vi key artanis.tar.gz 'ubuntu@'$i':/home/ubuntu/'
ssh -vi key 'ubuntu@'$i tar -xvzf artanis.tar.gz
ssh -vi key -q 'ubuntu@'$i /home/ubuntu/artica/server_script $start $end $1 $2 $3 $let start=$start+10; let end=$end+10
done
